"""
Django settings for currency project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv

import os

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

CORE_TEMPLATES_DIR = os.path.join(BASE_DIR, 'core/templates')
WSGI_APPLICATION = 'currency.wsgi.application'
ROOT_URLCONF = 'currency.urls'
STATIC_URL = '/static/'

SECRET_KEY = 'secretKey123'

AV_KEY = os.getenv('ALPHA_VANTAGE_KEY')

API_KEY = os.environ.get('MY_API_KEY')
PG_HOST = os.environ.get('DB_HOST')
PG_NAME = os.environ.get('DB_NAME')
PG_USER = os.environ.get('DB_USER')
PH_PORT = os.environ.get('DB_PORT')
PG_PASS = os.environ.get('DB_PASS')

ALLOWED_HOSTS = []

DEBUG = True


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [CORE_TEMPLATES_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'HOST': PG_HOST,
        'NAME': PG_NAME,
        'USER': PG_USER,
        'PORT': PH_PORT,
        'PASSWORD': PG_PASS,
    }
}

INSTALLED_APPS = [
    'core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'core.middleware.MWare',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



